#Ex4

In [ ]:
import numpy as np

X = np.array(([2,9],[1,5],[3,6]),dtype = float)
y = np.array(([92],[86],[89]),dtype = float)
X = X/np.amax(X,axis = 0)
y = y/100

def sigmoid(x):
  return (1/(1+np.exp(-x)))

def derivatives_sigmoid(x):
  return x*(1-x)

epoch = 7000

Ir = 0.1
inputlayer_neuron = 2
hiddenlayer_neuron =3
output_neuron = 1

wh = np.random.uniform(size = (inputlayer_neuron,hiddenlayer_neuron))
bh=np.random.uniform(size=(1,hiddenlayer_neuron))
wout = np.random.uniform(size=(hiddenlayer_neuron,output_neuron))
bout = np.random.uniform(size=(1,output_neuron))

for i in range(epoch):
  hinp1 = np.dot(X,wh)
  hinp = hinp1 + bh
  hlayer_act = sigmoid(hinp)
  outinp1 = np.dot(hlayer_act,wout)
  outinp = outinp1 + bout
  output = sigmoid(outinp)
  EO = y-output
  outgrad = derivatives_sigmoid(output)
  d_output = EO*outgrad
  EH = d_output.dot(wout.T)
  hiddengrad = derivatives_sigmoid(hlayer_act)
  d_hiddenlayer = EH*hiddengrad
  wout += hlayer_act.T.dot(d_output)*Ir
  bout += np.sum(d_output,axis=0,keepdims=True)*Ir
  wh += X.T.dot(d_hiddenlayer)*Ir
  bh += np.sum(d_hiddenlayer,axis=0,keepdims=True)*Ir

  print("Epoch: ",i)
  print("Actual Output: \n" + str(y))
  print("Predicted Output: \n",str(output))

Streaming output truncated to the last 5000 lines.
 [0.89]]
Predicted Output: 
 [[0.89464005]
 [0.88027084]
 [0.89390218]]
Epoch:  6445
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89464013]
 [0.88027068]
 [0.89390223]]
Epoch:  6446
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89464022]
 [0.88027052]
 [0.89390227]]
Epoch:  6447
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89464031]
 [0.88027036]
 [0.89390232]]
Epoch:  6448
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.8946404 ]
 [0.8802702 ]
 [0.89390237]]
Epoch:  6449
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89464049]
 [0.88027004]
 [0.89390241]]
Epoch:  6450
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89464058]
 [0.88026988]
 [0.89390246]]
Epoch:  6451
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89464067]
 [0.88026972]
 [0.89390251]]
Epoch:  6452
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Pred

#Ex5

In [ ]:
import csv
import random
import math

def loadCsv(filename):
  lines = csv.reader(open(filename,"r"))
  dataset = list(lines)
  for i in range(len(dataset)):
    dataset[i] = [float(x) for x in dataset[i]]
    return dataset

def splitDataset(dataset,splitRatio):
  trainSize = int(len(dataset)*splitRatio)
  trainSet = []
  copy =list(dataset)
  while len(trainSet) < trainSize:
    index = random.randrange(len(copy))
    trainSet.append(copy.pop(index))
    return [trainSet,copy]

def separateByClass(dataset):
  separated = {}
  for i in range(len(dataset)):
    vector = dataset[i]
    if vector[-1] not in separated :
      separated[vector[-1]].append(vector)
    return separated

def mean(numbers):
  return sum(numbers)/float(len(numbers))

def stdev(numbers):
  avg = mean(numbers)
  variance = sum([pow(x-avg,2) for x in numbers])/float(len(numbers)-1)
  return math.sqrt(variance)

def summarize(dataset):
  summaries = [(mean(attribute),stdev(attribute)) for attribute in zip(*dataset)]
  del summaries[-1]
  return summaries

def summarizeByClass(dataset):
  separated = separateByClass(dataset)
  summaries = {}

In [2]:
import csv
import random
import math

def loadCsv(filename):
    with open(filename, "r") as file:
        lines = csv.reader(file)
        dataset = list(lines)
        for i in range(len(dataset)):
            dataset[i] = [float(x) for x in dataset[i]]
    return dataset

def splitDataset(dataset, splitRatio):
    trainSize = int(len(dataset) * splitRatio)
    trainSet = []
    copy = list(dataset)
    while len(trainSet) < trainSize:
        index = random.randrange(len(copy))
        trainSet.append(copy.pop(index))
    return trainSet, copy

def separateByClass(dataset):
    separated = {}
    for vector in dataset:
        classValue = vector[-1]
        if classValue not in separated:
            separated[classValue] = []
        separated[classValue].append(vector)
    return separated

def mean(numbers):
    return sum(numbers) / float(len(numbers))

def stdev(numbers):
    avg = mean(numbers)
    variance = sum([(x - avg) ** 2 for x in numbers]) / float(len(numbers) - 1)
    return math.sqrt(variance)

def summarize(dataset):
    summaries = [(mean(attribute), stdev(attribute)) for attribute in zip(*dataset)]
    del summaries[-1]  # remove class label
    return summaries

def summarizeByClass(dataset):
    separated = separateByClass(dataset)
    summaries = {}
    for classValue, instances in separated.items():
        summaries[classValue] = summarize(instances)
    return summaries

def calculateProbability(x, mean, stdev):
    exponent = math.exp(-((x - mean) ** 2 / (2 * stdev ** 2)))
    return (1 / (math.sqrt(2 * math.pi) * stdev)) * exponent

def calculateClassProbabilities(summaries, inputVector):
    probabilities = {}
    for classValue, classSummaries in summaries.items():
        probabilities[classValue] = 1
        for i in range(len(classSummaries)):
            mean_, stdev_ = classSummaries[i]
            x = inputVector[i]
            probabilities[classValue] *= calculateProbability(x, mean_, stdev_)
    return probabilities

def predict(summaries, inputVector):
    probabilities = calculateClassProbabilities(summaries, inputVector)
    bestLabel, bestProb = None, -1
    for classValue, probability in probabilities.items():
        if bestLabel is None or probability > bestProb:
            bestProb = probability
            bestLabel = classValue
    return bestLabel

def getPredictions(summaries, testSet):
    predictions = []
    for vector in testSet:
        result = predict(summaries, vector)
        predictions.append(result)
    return predictions

def getAccuracy(testSet, predictions):
    correct = 0
    for i in range(len(testSet)):
        if testSet[i][-1] == predictions[i]:
            correct += 1
    return (correct / float(len(testSet))) * 100.0

def main():
    filename = '/content/drive/MyDrive/911124243058(SEM4)/ML/5data.csv'
    splitRatio = 0.67
    dataset = loadCsv(filename)
    trainingSet, testSet = splitDataset(dataset, splitRatio)

    print(f"Split {len(dataset)} rows into train={len(trainingSet)} and test={len(testSet)}")

    summaries = summarizeByClass(trainingSet)
    predictions = getPredictions(summaries, testSet)
    accuracy = getAccuracy(testSet, predictions)

    print(f"Accuracy of the classifier is: {accuracy:.2f}%")

if __name__ == "__main__":
    main()


Split 10 rows into train=6 and test=4
Accuracy of the classifier is: 100.00%
